export type Vocabulary = Map<string, string>;
export const highLightVocabulary: any = [
  ['namespace', '<span style="color: #d73a49">namespace</span>'],
  ['interface', '<span style="color: #d73a49">interface</span>'],
  ['implements', '<span style="color: #d73a49">implements</span>'],
  ['function', '<span style="color: #d73a49">function</span>'],
  ['class', '<span style="color: #d73a49">class</span>'],
  ['return', '<span style="color: #d73a49">return</span>'],
  ['new', '<span style="color: #d73a49">new</span>'],
  ['export', '<span style="color: #d73a49">export</span>'],
  ['abstract', '<span style="color: #d73a49">abstract</span>'],
  ['extends', '<span style="color: #d73a49">extends</span>'],
  ['constructor', '<span style="color: #d73a49">constructor</span>'],
  ['this', '<span style="color: #d73a49">this</span>'],
  ['private', '<span style="color: #002ed7">private</span>'],
  ['protected', '<span style="color: #002ed7">protected</span>'],
  ['public', '<span style="color: #002ed7">public</span>'],
  ['let', '<span style="color: #002ed7">let</span>'],
  ['const', '<span style="color: #002ed7">const</span>'],
  ['<', '<span style="color: #002ed7">\<</span>'],
  ['>', '<span style="color: #002ed7">\></span>'],
  ['Array', '<span style="color: #002ed7">Array</span>'],
  ['Object', '<span style="color: #002ed7">Object</span>'],
  ['super', '<span style="color: #002ed7">super</span>'],
  ['import', '<span style="color: #002ed7">import</span>'],
  ['from', '<span style="color: #002ed7">from</span>'],
  ['switch', '<span style="color: #002ed7">switch</span>'],
  ['case', '<span style="color: #002ed7">case</span>'],
  ['default', '<span style="color: #002ed7">default</span>'],
  ['if', '<span style="color: #002ed7">if</span>'],
  ['else', '<span style="color: #002ed7">else</span>'],
  ['{', '<span style="color: #002ed7">{</span>'],
  ['}', '<span style="color: #002ed7">}</span>'],
  ['`', '<span style="color: #002ed7">`</span>'],
  ['void', '<span style="color: #059c00">void</span>'],
  ['string', '<span style="color: #059c00">string</span>'],
  ['number', '<span style="color: #059c00">number</span>'],
  ['boolean', '<span style="color: #059c00">boolean</span>'],
  ['enum', '<span style="color: #059c00">enum</span>'],
  ['any', '<span style="color: #059c00">any</span>'],
  ['null', '<span style="color: #059c00">null</span>'],
  ['undefined', '<span style="color: #059c00">undefined</span>'],
  ['never', '<span style="color: #059c00">never</span>'],
  ['set', '<span style="color: #9a0b9c">set</span>'],
  ['get', '<span style="color: #9a0b9c">get</span>'],
  [':', '<span>:</span>'],
  ['[', '<span>[</span>'],
  [']', '<span>]</span>'],
  ['\'', '<span>\'</span>'],
  ['\"', '<span>\"</span>'],
];
export const comboVocabulary: any = [
  ['class', '#0064D7'],
  ['extends', '#0064D7'],
  ['new', '#0064D7'],
  ['implements', '#0064D7'],
  ['function', '#0064D7'],
  ['interface', '#0064D7'],
  [':', '#059c00'],
];
